- name: Nettoyage des anciennes partitions
  shell: |
    for PART in $(lsblk -nr -o NAME {{ disk }} | grep -E "^$(basename {{ disk }})p?[0-9]+$"); do
      wipefs --all --force "/dev/$PART"
    done
  args:
    executable: /bin/bash

- name: Création de la table GPT
  parted:
    device: "{{ disk }}"
    label: gpt
    state: present

- name: Création des partitions
  shell: |
    parted -s {{ disk }} mkpart primary 2MiB 3MiB
    parted -s {{ disk }} set 1 bios_grub on
    parted -s {{ disk }} mkpart primary fat32 3MiB 553MiB
    parted -s {{ disk }} set 2 boot on
    parted -s {{ disk }} mkpart primary linux-swap 553MiB 4553MiB
    parted -s {{ disk }} mkpart primary ext4 4553MiB 100%