stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: redt974/site1:latest  # Docker Hub ou GitLab Registry

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE ./site1
    - docker push $DOCKER_IMAGE

deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
    - echo "$KUBECONFIG" | base64 -d > kubeconfig
    - export KUBECONFIG=$PWD/kubeconfig
    - kubectl apply -f k8s/
  only:
    - main

