ansible_become: true

# User to create (common/users role)
deploy_user: deploy
deploy_user_uid: 1001
deploy_user_groups: "sudo"

# Sudo role
sudo_group: sudo

# Firewall allowed ports (list)
firewall_allowed_ports:
  - 22
  - 80
  - 443
  - 53
  - 51820  # wireguard default

# Domain / DNS example
domain: app.local
dns_zone: app.local
dns_forwarders:
  - 8.8.8.8
  - 8.8.4.4

# WireGuard
wg_interface: wg0
wg_address: 10.10.10.1/24
wg_port: 51820
wg_clients:
  - name: laptop
    address: 10.10.10.101/32

# Nginx site
nginx_site_name: app.local
nginx_site_root: /var/www/app

# Hardening : Debian
ssh_port: 2222
disable_services:
  - avahi-daemon
  - cups
  - bluetooth
security_packages:
  - ufw
  - fail2ban
  - apparmor
  - apparmor-utils
  - auditd
  - unattended-upgrades
  - apt-listchanges