- name: Hardening Arch Linux à distance
  hosts: arch-vm
  become: true

  vars_prompt:

    - name: "admin_user"
      prompt: "Nom de l'utilisateur admin"
      default: "localadm"
      private: no

    - name: "rescue_user"
      prompt: "Nom de l'utilisateur de secours"
      default: "rescue"
      private: no

    - name: "grub_user"
      prompt: "Nom d'utilisateur pour protéger GRUB"
      default: "grub"
      private: no

    - name: "grub_password"
      prompt: "Mot de passe pour GRUB"
      private: yes
      confirm: true

  roles:
    - arch-hardened
