- name: Monter les partitions
  block:
    - name: /
      mount:
        src: "{{ disk }}4"
        path: /mnt
        fstype: ext4
        state: mounted
    - name: /boot
      file:
        path: /mnt/boot
        state: directory
    - name: Boot
      mount:
        src: "{{ disk }}2"
        path: /mnt/boot
        fstype: vfat
        state: mounted