- name: Installer le système de base
  command: >
    pacstrap /mnt base base-devel linux linux-firmware vim sudo openssh grub dhcpcd --noconfirm

- name: Générer fstab
  command: genfstab -U /mnt >> /mnt/etc/fstab

- name: Installer Python dans le système Arch (Ansible)
  command: arch-chroot /mnt pacman -Sy --noconfirm python