---
- name: Ensure ufw is installed
  package:
    name:
      - ufw
    state: present
  when: ansible_facts['os_family'] in ['Debian','Archlinux','RedHat']

- name: Ensure ufw is installed
  package:
    name: ufw
    state: present
  when: ansible_facts['os_family'] in ['Debian', 'Archlinux', 'RedHat']

- name: Ensure ufw default deny incoming
  shell: ufw default deny incoming
  register: ufw_default_deny
  changed_when: "'changed' in ufw_default_deny.stdout or ufw_default_deny.rc == 0"
  when: ansible_facts['os_family'] in ['Debian', 'Archlinux', 'RedHat']

- name: Allow required ports via ufw
  shell: ufw allow {{ item }}
  loop: "{{ firewall_allowed_ports }}"
  when: ansible_facts['os_family'] in ['Debian', 'Archlinux', 'RedHat']

- name: Enable ufw
  shell: ufw --force enable
  when: ansible_facts['os_family'] in ['Debian', 'Archlinux', 'RedHat']
