- name: Installation Arch Linux à distance
  hosts: arch-vm
  become: true

  vars_prompt:
    - name: "disk"
      prompt: "Nom du disque (ex: /dev/sda)"
      default: "/dev/sda"
      private: no

    - name: "hostname"
      prompt: "Nom de la machine (hostname)"
      default: "archlinux"
      private: no

    - name: "locale"
      prompt: "Locale système (ex: fr_FR.UTF-8)"
      default: "fr_FR.UTF-8"
      private: no

    - name: "timezone"
      prompt: "Fuseau horaire (ex: Europe/Paris)"
      default: "Europe/Paris"
      private: no

    - name: "user_name"
      prompt: "Nom de l'utilisateur à créer"
      default: "thib"
      private: no

    - name: "user_password"
      prompt: "Mot de passe de l'utilisateur"
      private: yes
      confirm: true

  roles:
    - archinstall
